[package]
name = "cycles-simple"
version = "0.11.4"
description = "A library for topping child canister (such as CanDB partition canisters) cycles from a parent canister"
repository = "https://github.com/vporton/cycles-simple"
keywords = [ "cycles", "canisters", "topping", "sending" ]
license = "MIT"

[dependencies]
stablehashmap = "1.0.0"
base = "0.11.1"